<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "chart"
 *
 * Auto generated by Extension Builder 2021-07-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Ps14 Chart',
	'description' => 'Chart extension for inputting compressed air data into products',
	'category' => 'module',
	'author' => 'Christian Pschorr',
	'author_email' => 'pschorr.christian@gmail.com',
	'state' => 'beta',
	'version' => '2.0.0',
	'constraints' => [
		'depends' => [
			'typo3' => '12.0.0-12.4.99',
			'ps14_foundation' => '2.0.0-2.99.99',
			'flux' => '10.0.10-10.9.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];
