<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "chart"
 *
 * Auto generated by Extension Builder 2021-07-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Ps14 Chart',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Christian Pschorr',
	'author_email' => 'pschorr.christian@gmail.com',
	'state' => 'alpha',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => [
		'depends' => [
			'typo3' => '10.4.0-10.4.99',
			'xo' => '1.0.0-1.10.99',
			'flux' => '9.5.0-9.5.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];
